### ISSUE TITLE
Circular Import Detected in Venue Booking System

### ISSUE THREAD

**Issue by technovore007** [technovore007/Venue-Booking-App#1]
We are encountering a circular import issue in our Venue Booking System project. The circular import is causing conflicts and preventing the application from running as expected.

### **Details**
1. **Problem Description**:  
   When trying to run the application, we are getting import errors that indicate a circular dependency between certain modules. This is causing the application to fail to start and preventing users from logging in or accessing other features.

2. **Steps to Reproduce**:
   - Clone the repository and set up the environment as per the README instructions.
   - Run the login script (`python login_page.py`).
   - Observe the import error messages related to circular dependencies.

3. **Error Messages**:
   ```
   ImportError: cannot import name 'ModuleA' from 'moduleB' due to a circular import
   ```

4. **Affected Files**:
   - `login_page.py`
   - `common.py`
   - Other modules that import these files

5. **Current Behavior**:
   - The application fails to start due to import errors.
   - Users cannot log in or make bookings, which affects the usability of the system.

6. **Expected Behavior**:
   - The application should run without import errors, allowing users to log in, make bookings, and administrators to manage the system.

### **Analysis**
- The circular import occurs because `common.py` is being imported in multiple files, causing a loop of imports.
- This issue disrupts the flow of the program and prevents proper initialization of the application components.

### **Potential Solutions**
1. **Redesign of Imports**: 
   - Restructure the module dependencies to break the circular import.
   - Consider moving common functions and variables to a separate utility module that can be imported where needed without causing a circular reference.
   
2. **Conditional Imports**:
   - Use `if __name__ == "__main__"` to avoid circular imports during script execution.
   - Ensure that modules that don’t need to interact directly don’t import each other, or if they must, it should be done in a controlled manner.

### **Additional Information**
- Provide any relevant screenshots of the errors or the code that is causing the issue.
- Mention any debugging steps you’ve already taken to diagnose this problem.

## **Tasks to Resolve**:
- [x] Review the current module import structure.
- [x] Identify modules that are causing the circular import.
- [x] Apply the suggested solutions to eliminate the circular dependency.
- [x] Test the changes to ensure the application starts without errors.

---

**Comment by technovore007** [comment]
Issue has been resolved !
